variables:
  GIT_DEPTH: 1

stages:
  - test
  - build
  - staging
  - production

test:lint:
  image: registry.gitlab.com/idsdeveloper/kejar/docker:latest
  stage: test
  script:
    - cp .env.example .env
    - composer install
    - composer lint:check
  cache:
    key: composer
    paths:
      - vendor/
  except:
    - master

build:app:
  image: registry.gitlab.com/idsdeveloper/kejar/docker:latest
  stage: build
  script:
    - composer install --optimize-autoloader --no-dev --no-suggest --prefer-dist --no-scripts --no-plugins
    - yarn install
    - yarn production
    - rm -rf ./tests
    - rm -rf ./database
    - rm -rf ./storage
    - cd $CI_PROJECT_DIR/deploy/output
    - find $CI_PROJECT_DIR -printf "%P\n" -type f -o -type l -o -type d | tar --exclude='.*' --exclude='*.xml'
      --exclude='deploy' -czf build.tar.gz --no-recursion -C $CI_PROJECT_DIR -T -
  artifacts:
    expire_in: 1 day
    paths:
    - deploy/output/build.tar.gz
  cache:
    key: composer
    paths:
      - vendor/
      - node_modules/
    policy: pull
  only:
    - master
    - /^staging-.*$/
    - /^release-.*$/

staging:deploy:
  image: williamyeh/ansible:ubuntu18.04
  stage: staging
  script:
    - cd deploy
    - echo "$DEPLOYER_PRIVATE_KEY" > staging.key
    - chmod 400 staging.key
    - export ANSIBLE_HOST_KEY_CHECKING=false
    - ansible-playbook -v -i staging playbook.yml
    - rm -rf staging.key
  cache: {}
  dependencies:
    - build:app
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^staging-.*$/'
      when: manual
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: on_success
  environment:
    name: staging
    url: https://matrik-sushi.kejar.id

production:deploy:
  image: williamyeh/ansible:ubuntu18.04
  stage: production
  script:
    - cd deploy
    - echo "$DEPLOYER_PRIVATE_KEY" > production.key
    - chmod 400 production.key
    - export ANSIBLE_HOST_KEY_CHECKING=false
    - ansible-playbook -v -i production playbook.yml
    - rm -rf production.key
  cache: {}
  dependencies:
    - build:app
  only:
    - /^release-.*$/
  environment:
    name: production
    url: https://matrikulasi.kejar.id

